layout_spectrum: 0.7861162
typography_spectrum: 0.3964906
color:
  saturation: 0.2388847
  lightness: 0.5134439
  brandStrength: 0.003253334
  rhythmicContrast: 0.9529268
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: A.I Dyk
